config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  get '/sessions/new' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/account' => 'users#show'

  resources :movies
  resources :directors
  resources :actors
  resources :users


end

app/models/actor.rb
class Actor < ActiveRecord::Base

  
end

app/models/director.rb
class Director < ActiveRecord::Base

  has_many :movies
  
  # General form:
  # has_many :movies, class_name: 'Movie', foriegn_key: 'director_id'

  # def movies
  #   Movie.where(director_id: self.id).order('title')
  # end

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  belongs_to :director
  has_many :roles
  has_many :actors, :through => :roles

  # validates_presence_of :title
  validates :title, presence: true, uniqueness: true

  # General form:
  # belongs_to :director, class_name: 'Director', foreign_key: :director_id

  # def director
  #   Director.find_by(id: self.director_id)
  # end

  # def roles
  #   Role.where(movie_id: self.id)
  # end

  # def actors
  #   roles.collect do |role|
  #     role.actor
  #   end
  # end

end

app/models/role.rb
class Role < ActiveRecord::Base

  belongs_to :movie
  belongs_to :actor

  # def actor
  #   Actor.find(self.actor_id)
  # end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, :email, :password, presence: true
  validates :password, confirmation: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

  def index
    @directors = Director.order("name asc")
  end

  def show
    @director = Director.find_by(:id => params["id"])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :find_movie, only: [:show, :update, :edit, :destroy]

  def find_movie
    @movie = Movie.find(params["id"])
  end

  def update
    @movie.title = params[:title]
    @movie.year = params[:year]
    @movie.save
    redirect_to root_url
  end

  def edit
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new
    @movie.title = params["title"]
    @movie.year = params["year"]
    @movie.director_id = params["director_id"]

    if @movie.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
    if params["keyword"].present?
      k = params["keyword"].strip
      @movies = Movie.where("title LIKE '%#{k}%'")
    else
      @movies = Movie.all
    end

    respond_to do |format|
      format.html do
        render 'index'
      end
      format.json do
        render :json => @movies
      end
      format.xml do
        render :xml => @movies
      end
    end

  end

  def destroy
    @movie.delete
    redirect_to "/movies"
  end

  def show
    session["history"] ||= []
    session["history"] << @movie.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def destroy
    # sessions[:user_id] = nil
    reset_session
    redirect_to root_url, notice: "See ya!"
  end
  def create
    user = User.find_by_email(params["email"])

    if user
      if user.password == params["password"]
        session[:user_id] = user.id
        flash[:notice] = "Welcome Back, #{user.name}!"
        redirect_to root_url
      else
        render 'new'
      end
    else
      render 'new'
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    if @user.save
      flash[:notice] = "Thanks for signing up!"
      redirect_to movies_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]

    if @user.password.present? && @user.password == params[:password_confirmation]
      if @user.save
        flash[:notice] = "Account updated successfully."
        redirect_to user_url(@user.id)
      else
        render 'edit'
      end
    else
      @user.errors.add(:password, "does not match")
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/directors/index.html.erb
<h1>Directors</h1>

<ul>
<% @directors.each do |d| %>
  <li><%= link_to d.name, "/directors/#{d.id}" %></li>
<% end %>
</ul>

app/views/directors/show.html.erb
<h1><%= @director.name %></h1>


<h4>Filmography:</h4>

<% @director.movies.each do |movie| %>
  <h4><%= link_to movie.title, "/movies/#{movie.id}" %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebFlix</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js' %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" %>

  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">WebFlix</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/movies">Movies</a></li>
          <li><a href="/directors">Directors</a></li>
          <li><a href="/actors">Actors</a></li>

          <form action="/movies" class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input value="<%= params[:keyword] %>" name="keyword" type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if session[:user_id] %>
            <li>Howdy, <%= User.find(session[:user_id]).name %></li>
          <% end %>
          <li><a href="/users/new">Sign Up</a></li>
          <li><a href="/sessions/new">Sign In</a></li>
          <li><a href="/account">My Account</a></li>
          <li><a href="/logout">Sign Out</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">

    <% if flash[:notice].present? %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/movies/edit.html.erb
<h1>Edit a New Movie</h1>

<%= form_tag "/movies/#{@movie.id}", :method => "patch" do %>
  <div>
    <label>Movie Title:</label>
    <input type="text" name="title" value="<%= @movie.title %>">
  </div>

  <div>
    <label>Movie Year:</label>
    <input type="text" name="year" value="<%= @movie.year %>">
  </div>

  <select name="director_id">
    <% Director.all.each do |d| %>
      <option value="<%= d.id %>"><%= d.name %></option>
    <% end %>
  </select>

  <input type="submit" value="Update Movie">

<% end %>

app/views/movies/index.html.erb
<h1>Movies
  <small>
    <a class="btn btn-success pull-right" href="/movies/new">Add a New Movie</a>
  </small>
</h1>

<% if session["history"] %>
  <p><small><%= link_to "Clear My Viewing History", "#" %></small></p>
  <div class="recent clearfix">
    <h4>Your Recently Viewed Items</h4>
    <% recent_movies = Movie.find(session["history"]) %>
    <% recent_movies.each do |movie| %>
      <%= link_to image_tag(movie.poster_url, height: '200px'), movie %>
    <% end %>
  </div>
<% end %>

<p><%= @movies.count %> movies shown.</p>

<table class='table table-striped'>
  <thead>
    <tr>
      <th width="30%">Title</th>
      <th width="30%">Directed By</th>
      <th>Year</th>
      <th></th>
      <th></th>
    </tr>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= link_to movie.title, "/movies/#{movie.id}" %>
        </td>
        <td>
          <% if movie.director_id != nil %>
            <%= link_to Director.find_by(:id => movie.director_id).name, "/directors/#{movie.director_id}" %>
          <% end %>
        </td>
        <td><%= movie.year %></td>

        <td><%= link_to "Delete", "/movies/#{movie.id}", :method => "delete" %></td>
        <td><%= link_to "Edit", "/movies/#{movie.id}/edit" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<h1>Add a New Movie</h1>

<% if @movie.errors.any? %>
<p>
  Yo there seems to be a problem.
</p>
<% end %>

<%= form_tag "/movies" do %>
  <div>
    <label>Movie Title:</label>
    <input type="text" name="title" value="<%= @movie.title %>">
  </div>

  <div>
    <label>Movie Year:</label>
    <input type="text" name="year" value="<%= @movie.year %>">
  </div>

  <select name="director_id">
    <% Director.all.each do |d| %>
      <option value="<%= d.id %>"><%= d.name %></option>
    <% end %>
  </select>

  <input type="submit" value="Add Movie">

<% end %>

app/views/movies/show.html.erb
<div class="movie">
  <h2><%= @movie.title %></h2>

  <p>
    <span class="rating">Rated <%= @movie.rated %></span>
    <%= @movie.runtime %>
  </p>

  <%= image_tag @movie.poster_url %>

  <h3>Directed by: <%= @movie.director.name %></h3>

  <p><%= @movie.plot %></p>

  <h3>Cast</h3>
  <ul>
    <% @movie.actors.each do |actor| %>
      <li>
        <%= actor.name %>
      </li>
    <% end %>
  </ul>





</div>

app/views/users/index.html.erb
<div class="page-header">
  <h1>User Accounts</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <td>Name</td>
      <td>Email Address</td>
      <td>Password</td>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign Up</h1>
</div>

<% if @user.errors.any? %>
  <ul class="list-unstyled text-danger">
    <% @user.errors.full_messages.each do |msg| %>
      <li><strong><%= msg %></strong></li>
    <% end %>
  </ul>
<% end %>

<%= form_tag users_path do %>

  <p>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
  </p>

  <p>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </p>

  <p>
    <%= label_tag :password %>
    <%= text_field_tag :password %>
  </p>

  <p>
    <%= label_tag :password_confirmation, "Password Again" %>
    <%= text_field_tag :password_confirmation %>
  </p>

  <%= submit_tag "Sign Me Up!" %>

<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <%= link_to "Edit", edit_user_path(@user.id), class: 'btn btn-md btn-primary pull-right' %>
  <h1>My Account</h1>
</div>


<p>
  <strong>Name:</strong> <%= @user.name %>
</p>

<p>
  <strong>Email address on file:</strong> <%= @user.email %>
</p>

<p>
  <strong>Current password:</strong> <%= @user.password %>
</p>